apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  #namespace: "{{ .Values.app.namespace }}"
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: "{{ .Values.app.image }}"
        ports:
        - containerPort: 8080

