apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  # namespace: "{{ .Values.app.namespace }}"
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    NodePort: 30008

